# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: name-tests-test
        args: [--pytest-test-first]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]

-   repo: https://github.com/klen/pylama
    rev: 8.4.1
    hooks:
    -   id: pylama
        args: [--options pyproject.toml]

-   repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        files: "\\.(py)$"
        args: [--in-place,--remove-unused-variables,--remove-all-unused-imports]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        # additional_dependencies: [types-all]
        additional_dependencies: [types-PyYAML]
