version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    resource_class: medium
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pytest
          name: Running Tests

workflows:
  personal_workflow:
    jobs:
      - build-and-test
