name: publish-docker
on: workflow_dispatch
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag janikva/nba-game-prediction:latest
      - name: Push the tagged Docker image
        run: docker push janikva/nba-game-prediction:latest
